config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'users/show'
  get 'search/search'
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end

  root to: "events#index"
  resources :events do
    resources :ticket_comments, only: [:create, :destroy]
    resources :event_comments, only: [:create, :destroy]
  end


  get 'search/search'
  get '/search', to: 'search#search'
  resources :users, only: [:show, :edit, :update]
  get "/past_events/users/:id" => "users#past_events"
  get "/future_events/users/:id" => "users#future_events"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :ticket_comments, dependent: :destroy
  attachment :profile_image

  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  has_many :event_comments, dependent: :destroy

  validates :name, length: { in: 2..20 }, presence: true, uniqueness: true
  

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @ticket_comments = @user.ticket_comments

    # 以下はコメント機能
    @currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @user_room = UserRoom.new
      end
    end
    # 以上はコメント機能
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールの更新が完了しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def past_events
    @user = User.find(params[:id])
  end

  def future_events
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>プロフィール</h1>

      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:</br>
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <p>
            <%= f.label :名前 %></br>
            <%= f.text_field :name, autofocus: true, id:"user_name" %>
          </p>
        </div>
        <div class="form-group">
          <p>
            <%= f.label :プロフィール画像 %></br>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </p>
        </div>
        <div class="form-group">
          <p>
            <%= f.label :自己紹介 %></br>
            <%= f.text_area :introduction, autofocus: true, id:"user_introduction" %>
          </p>
        </div>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/expect_index.html.erb
<div class="container">
  <h1><%= @user.name %>さんの開催予定イベント</h1>
  <% @user.events.each do |event| %>
    <% if event.start_at > Time.zone.now %>
      <div class='card mt-4'>
        <h5 class='card-header'>
          <%= link_to event.name, event_path(event) %>
        </h5>
        <div class="card-text">
          <p class='mt-3'><%= l(event.start_at, format: :long) %> ~ <%= l(event.end_at, format: :long) %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/future_events.html.erb
<div class="container">
  <h1><%= @user.name %>さんの開催予定イベント</h1>
  <% @user.events.each do |event| %>
    <% if event.start_at > Time.zone.now %>
      <div class='card mt-4'>
        <h5 class='card-header'>
          <%= link_to event.name, event_path(event) %>
        </h5>
        <div class="card-text">
          <p class='mt-3'><%= l(event.start_at, format: :long) %> ~ <%= l(event.end_at, format: :long) %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/past_events.html.erb
<div class="container">
  <h1><%= @user.name %>さんが過去に開催したイベント</h1>
  <% @user.events.each do |event| %>
    <% if event.end_at < Time.zone.now %>
      <div class='card mt-4'>
        <h5 class='card-header'>
          <%= link_to event.name, event_path(event) %>
        </h5>
        <div class="card-text">
          <p class='mt-3'><%= l(event.start_at, format: :long) %> ~ <%= l(event.end_at, format: :long) %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/past_index.html.erb
<div class="container mt-3">
  <% @user.events.each do |event| %>
  <div class='card mt-4'>
    <div class='card-header'>
      <%= event.name %>
    </div>
    <div class='card-text'>
      <%= event.introduction %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="card mb-4">
    <div class="card-header " >
      <%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: "jpeg",fallback: "no_image.jpg" %>
      <h5><%= @user.name %></h5>
      </div>
    <div class="card-text">
      <h5 class="mt-3">自己紹介</h5>
      <p><%= @user.introduction %></p>
      <hr>
      <% if @user == current_user %>
        <h5 class='mt-3'>参加予定イベント一覧</h5>
        <% @user.ticket_comments.first(2).each do |ticket_comment| %>
          <% if ticket_comment.event.end_at > Time.zone.now %>
            <p> <%= link_to ticket_comment.event.name, event_path(ticket_comment.event) %></p>
          <% end %>
        <% end %>
      <hr>
      <% end %>
      <p class='mt-3'>
        <span style='font-size: 20px'>開催予定イベント</span>
        <%= link_to 'すべて見る', controller: 'users', action: 'future_events', id: @user.id %>
      </p>
      <% @user.events.first(2).each do |event| %>
        <% if event.start_at >= Time.zone.now %>
          <p class='mt-3'><%= link_to event.name, event_path(event) %></p>
        <% end %>
      <% end %>
      <hr>
      <p class='mt-3'>
        <span style='font-size: 20px'>過去の開催イベント</span>
        <%= link_to 'すべて見る', controller: 'users', action: 'past_events', id: @user.id %>
      </p>
      <% @user.events.first(2).each do |event| %>
        <% if event.end_at < Time.zone.now %>
          <p class='mt-3'><%= link_to event.name, event_path(event) %></p>
        <% end %>
      <% end %>
    </div>
  </div>
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(current_user), class: "  fas fa-user-cog edit_user_27083" %></p>
  <% end %>

<!--チャット機能-->

  <% if @user.id != current_user.id %>
    <% if @isRoom == true %>
      <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
    <% else %>
      <%= form_for @room do |f| %>
        <%= fields_for @user_room do |e| %>
          <%= e.hidden_field :user_id, :value=> @user.id %>
        <% end %>
        <%= f.submit "チャットを始める" %>
      <% end %>
    <% end %>
  <% end %>
</div>