config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'users/show'
  get 'search/search'
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end

  root to: "events#index"
  resources :events do
    resources :ticket_comments, only: [:create, :destroy]
    resources :event_comments, only: [:create, :destroy]
  end


  get 'search/search'
  get '/search', to: 'search#search'
  resources :users, only: [:show, :edit, :update]
  get "/past_events/users/:id" => "users#past_events"
  get "/future_events/users/:id" => "users#future_events"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :ticket_comments, dependent: :destroy
  has_many :event_comments, dependent: :destroy

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :introduction, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_end_check
  validate :start_check

  def start_end_check
    errors.add(:end_at, "は開始時刻より遅い時間を選択してください") if start_at > end_at
  end

  def start_check
    errors.add(:start_at, "は現在の日時より遅い時間を選択してください") if start_at < Time.now
  end

  def self.search_for(content) #検索機能
    Event.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

app/models/ticket_comment.rb
class TicketComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :ticket_comments, dependent: :destroy
  attachment :profile_image

  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  has_many :event_comments, dependent: :destroy

  validates :name, length: { in: 2..20 }, presence: true, uniqueness: true
  

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      flash[:notice] = "イベントの作成が完了しました"
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def index
    @events = Event.where("start_at > ?", Time.zone.now).order(:start_at).page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
    @ticket_comment = TicketComment.new
    # @ticket_comment_destroy = TicketComment.find_by(event_id: params[:id])
    if user_signed_in?
      @applied_user_ticket_comment = TicketComment.where(event_id: params[:id], user_id: current_user.id)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "更新しました"
    else
      render :edit
    end
  end

  def dedtroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path, notice: "削除しました"
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :introduction, :start_at, :end_at)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    if UserRoom.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :message, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = UserRoom.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if UserRoom.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @user_rooms = @room.user_rooms
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params[:model]
    @content = params[:content]
    @records = Event.search_for(@content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @ticket_comments = @user.ticket_comments

    # 以下はコメント機能
    @currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @user_room = UserRoom.new
      end
    end
    # 以上はコメント機能
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールの更新が完了しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def past_events
    @user = User.find(params[:id])
  end

  def future_events
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tickets_comment_helper.rb
module TicketsCommentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<% now = Time.zone.now %>

<div class="container">
<h1 class="mt-2">イベント情報編集</h1>

<%= form_with model: @event, local:true do |f| %>

  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li style="color:red">
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :イベント名 %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :イベント開催場所 %>
    <%= f.text_field :place, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :イベント開始時間 %>
    <div>
      <%= f.datetime_select :start_at, start_year: now.year, end_year: now.year + 2 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :イベント終了時間 %>
    <div>
      <%= f.datetime_select :end_at, start_year: now.year, end_year: now.year + 2 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :イベント詳細 %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>

<% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h1>イベント一覧</h1>
    </div>
    <div class="search-form text-right mt-3 col-4">
      <%= form_with url: search_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :content %>
        <%= f.submit '検索' %>
      <% end %>
    </div>
  </div>

  <% @events.each do |event| %>
    <div class="card mb-4">
      <h5 class="card-header"><%= link_to event.name, event_path(event.id) %></h5>
      <div class="card-text">
        <p class="mt-3"><%= l(event.start_at, format: :long) %> ~ <%= l(event.end_at, format: :long) %></p>
      </div>
    </div>
  <% end %>
  <%= paginate @events%>
</div>

app/views/events/new.html.erb
<% now = Time.zone.now %>

<div class='container'>
  <h1>イベント作成</h1>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li style="color:red">
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @event, local:true do |f| %>

    <div class="form-group mt-5">
      <%= f.label :イベント名 %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :開催場所 %>
      <%= f.text_field :place, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :イベント開始日時 %>
      <div>
        <%= f.datetime_select :start_at, start_year: now.year, end_year: now.year + 2  %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :イベント終了日時 %>
      <div>
        <%= f.datetime_select :end_at, start_year: now.year, end_year: now.year + 2  %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :イベント詳細 %>
      <%= f.text_area :introduction, class: "form-control" %>
    </div>

    <%= f.submit "イベントの作成" %>

  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1 class="mb-5"><%= @event.name %></h1>
  <div class="row">
    <div class="col-8">
      <div class="card mb-4">
        <h5 class="card-header" >イベント内容</h5>
        <div class="card-text">
          <p class="mt-3"><%= @event.introduction %></p>
        </div>
      </div>

      <div class="card mb-4">
        <h5 class="card-header">開催時間</h5>
        <div class="card-text">
          <p class="mt-3"><%= l(@event.start_at, format: :long) %> ~ <%= l(@event.end_at, format: :long) %> </p>
        </div>
      </div>

      <div class="card mb-4">
        <h5 class="card-header">開催場所</h5>
        <div class="card-text">
          <p class="mt-3"><%= @event.place %></p>
        </div>
      </div>

      <div class="card mb-2">
        <h5 class="card-header">主催者</h5>
        <div class="card-text">
          <p class="mt-3"><%= link_to @event.user.name, user_path(@event.user) %></p>
        </div>
      </div>
    </div>

    <div class="col-4">
      <!--イベントの主催者が現在のユーザー。かつ、イベントの開催日時が現在の日時以降-->
      <% if @event.user == current_user && @event.start_at > Time.zone.now %>
        <%= link_to "イベントを編集する", edit_event_path(@event.id), class: "btn btn-info btn-lg btn-block" %>
        <%= link_to "イベントを削除する", event_path(@event.id), class: "btn btn-danger btn-lg btn-block ", method: :delete, "data-confirm" => "本当に削除しますか？" %>
      <% end %>

      <% if user_signed_in? %>
        <!--現在のユーザーのコメントがない。サインインしている。イベントの開催日時が現在の日時以降-->
        <% if user_signed_in? && @applied_user_ticket_comment.blank? && @event.start_at > Time.zone.now %>
          <button type="button" class="btn btn-primary btn-block btn-lg" data-toggle="modal" data-target="#createTicket">
            参加する
          </button>

          <div class="modal fade" id="createTicket">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="exampleModalLabel">参加コメント</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <%= form_with(model:[@event,@ticket_comment], local: true) do |f| %>
                  <div class="modal-body">
                    <% if @event.errors.any? %>
                      <ul>
                        <% @event.errors.full_messages.each do |message| %>
                          <li style="color:red">
                            <%= message %>
                          </li>
                        <% end %>
                      </ul>
                    <% end %>
                    <%= f.text_field :comment, class: "form-control", placeholder: "コメントをここに" %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                    <%= f.submit "送信", class: "btn btn-primary" %>
                  </div>
                <% end %>

              </div>
            </div>
          </div>
        <!--イベントの開催日時が現在の日時以降-->
        <% elsif @event.start_at > Time.zone.now %>
          <%= link_to "参加をキャンセルする", event_ticket_comment_path(@event), method: :delete, "data-confirm" => "本当にキャンセルしますか？", class: "btn btn-danger btn-block btn-lg" %>
        <% end %>
      <% end %>
      <hr>
      <div class="card mb-2">
        <h5 class="card-header">参加者<%= @event.ticket_comments.count %>名</h5>
        <ul class="list-group list-group-flush">
          <% @event.ticket_comments.each do |ticket_comment| %>
            <li class="list-group-item">
              <%= link_to user_path(ticket_comment.user) do %>
                <%= attachment_image_tag ticket_comment.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
              <%= link_to ticket_comment.user.name, user_path(ticket_comment.user) %> : <%= ticket_comment.comment %>
            </li>
          <% end %>
        </ul>
      </div>

      <!--イベントの終了日時が現在の日時よりも前の場合-->
      <% if @event.end_at < Time.zone.now %>
        <div class="card mb-2">
          <h5 class="card-header">コメント<%= @event.event_comments.count %>件</h5>
          <ul class="list-group list-group-flush">
            <% @event.event_comments.each do |event_comment| %>
              <li class="list-group-item">
                <%= event_comment.user.name %>:
                <%= event_comment.comment %>
                <% if event_comment.user == current_user %>
                  <div class="comment-delete">
                    <%= link_to "削除", event_event_comment_path(event_comment.event, event_comment), method: :delete %>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <%= form_with(model:[@event,@event_comment], local: true) do |f| %>
          <%= f.text_field :comment, class: "form-control", placeholder: "コメントをここに" %>
          <%= f.submit "送信", class: "btn btn-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">

  <% @user_rooms.each do |e| %>
    <% if e.user != current_user %>
  　   <h5><strong><%= link_to e.user.name, user_path(e.user.id) %>さんとのチャット</strong></h5>
  　<% end %>
  <% end %>

  <hr>
  <% if @messages.present? %>
    <% @messages.each do |m| %>
      <% if m.user == current_user %>
        <div class="text-right">
          <strong><%= m.message %></strong>
          <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.name %>さん</a></strong></small>
        </div>
      <% else %>
        <div class="text-left">
          <strong style="text-align: left;"><%= m.message %></strong>
          <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.name %>さん</a></strong></small>
        </div>
      <% end %>
      <hr>
    <% end %>
  <% else %>
    <h3 class="text-center">メッセージはまだありません</h3>
  <% end %>

  <div class="text-center">
    <%= form_for @message do |f| %>
      <%= f.text_field :message, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <%= f.submit "送信" %>
    <% end %>
  </div>

</div>