config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'users/show'
  get 'search/search'
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end

  root to: "events#index"
  resources :events do
    resources :ticket_comments, only: [:create, :destroy]
    resources :event_comments, only: [:create, :destroy]
  end


  get 'search/search'
  get '/search', to: 'search#search'
  resources :users, only: [:show, :edit, :update]
  get "/past_events/users/:id" => "users#past_events"
  get "/future_events/users/:id" => "users#future_events"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :ticket_comments, dependent: :destroy
  has_many :event_comments, dependent: :destroy

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :introduction, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_end_check
  validate :start_check

  def start_end_check
    errors.add(:end_at, "は開始時刻より遅い時間を選択してください") if start_at > end_at
  end

  def start_check
    errors.add(:start_at, "は現在の日時より遅い時間を選択してください") if start_at < Time.now
  end

  def self.search_for(content) #検索機能
    Event.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

app/models/ticket_comment.rb
class TicketComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :ticket_comments, dependent: :destroy
  attachment :profile_image

  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  has_many :event_comments, dependent: :destroy

  validates :name, length: { in: 2..20 }, presence: true, uniqueness: true
  

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      flash[:notice] = "イベントの作成が完了しました"
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def index
    @events = Event.where("start_at > ?", Time.zone.now).order(:start_at).page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
    @ticket_comment = TicketComment.new
    # @ticket_comment_destroy = TicketComment.find_by(event_id: params[:id])
    if user_signed_in?
      @applied_user_ticket_comment = TicketComment.where(event_id: params[:id], user_id: current_user.id)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "更新しました"
    else
      render :edit
    end
  end

  def dedtroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path, notice: "削除しました"
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :introduction, :start_at, :end_at)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = UserRoom.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if UserRoom.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @user_rooms = @room.user_rooms
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params[:model]
    @content = params[:content]
    @records = Event.search_for(@content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @ticket_comments = @user.ticket_comments

    # 以下はコメント機能
    @currentUserEntry = UserRoom.where(user_id: current_user.id)
    @userEntry = UserRoom.where(user_id: @user.id)
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @user_room = UserRoom.new
      end
    end
    # 以上はコメント機能
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールの更新が完了しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def past_events
    @user = User.find(params[:id])
  end

  def future_events
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>AwesomeEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Awesome Events</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>

                <li class="nav-item">
                  <%= link_to "イベント一覧", root_path, class: "nav-link text-light" %>
                </li>

                <li class="nav-item">
                  <%= link_to "イベントの作成", new_event_path, class: 'nav-link text-light' %>
                </li>

                <li>
                  <%= link_to 'マイページ', user_path(current_user.id), class: "nav-link text-light" %>
                </li>

                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: ' nav-link text-light' %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to "イベント一覧", root_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: ' nav-link text-light' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

    <main class="mb-auto">
      <%= yield %>
    </main>


  </body>
</html>